# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\"\x18\n\nPayInvoice\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1b\n\tPayStatus\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\x36\n\x0eServicePayment\x12$\n\tverifyPay\x12\x0b.PayInvoice\x1a\n.PayStatusb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PAYINVOICE._serialized_start=17
  _PAYINVOICE._serialized_end=41
  _PAYSTATUS._serialized_start=43
  _PAYSTATUS._serialized_end=70
  _SERVICEPAYMENT._serialized_start=72
  _SERVICEPAYMENT._serialized_end=126
# @@protoc_insertion_point(module_scope)
